import { CommunityChallenge, MicroGoal } from '@/types';

export const COMMUNITY_CHALLENGES: CommunityChallenge[] = [
  {
    id: 'cc-90-days-sober',
    title: '90 Days Sober',
    description: 'Stay sober for 90 consecutive days and build lasting recovery habits.',
    category: 'recovery',
    duration: '90 days',
    xpValue: 5000,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 247,
    badgeId: 'badge-90-days-sober',
    microGoals: [
      { id: 'mg-1', title: 'Complete 7 days', completed: false, xpValue: 500 },
      { id: 'mg-2', title: 'Complete 30 days', completed: false, xpValue: 1500 },
      { id: 'mg-3', title: 'Complete 60 days', completed: false, xpValue: 2000 },
      { id: 'mg-4', title: 'Complete 90 days', completed: false, xpValue: 1000 },
    ],
  },
  {
    id: 'cc-75-hard',
    title: '75 Hard Challenge',
    description: 'Complete 75 days of strict discipline: 2 workouts, diet, water, reading, and progress photos.',
    category: 'discipline',
    duration: '75 days',
    xpValue: 4500,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 892,
    badgeId: 'badge-75-hard',
    microGoals: [
      { id: 'mg-1', title: 'Complete Week 1', completed: false, xpValue: 400 },
      { id: 'mg-2', title: 'Complete Week 4', completed: false, xpValue: 800 },
      { id: 'mg-3', title: 'Complete Week 8', completed: false, xpValue: 1200 },
      { id: 'mg-4', title: 'Complete 75 days', completed: false, xpValue: 2100 },
    ],
  },
  {
    id: 'cc-read-5-books',
    title: 'Read 5 Books in 60 Days',
    description: 'Expand your mind by reading 5 complete books in just 2 months.',
    category: 'mental',
    duration: '60 days',
    xpValue: 3000,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 1543,
    badgeId: 'badge-bookworm',
    microGoals: [
      { id: 'mg-1', title: 'Finish Book 1', completed: false, xpValue: 600 },
      { id: 'mg-2', title: 'Finish Book 2', completed: false, xpValue: 600 },
      { id: 'mg-3', title: 'Finish Book 3', completed: false, xpValue: 600 },
      { id: 'mg-4', title: 'Finish Book 4', completed: false, xpValue: 600 },
      { id: 'mg-5', title: 'Finish Book 5', completed: false, xpValue: 600 },
    ],
  },
  {
    id: 'cc-social-butterfly',
    title: 'Social Butterfly Challenge',
    description: 'Meet 30 new people in 30 days and build your social network.',
    category: 'social',
    duration: '30 days',
    xpValue: 2000,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 634,
    badgeId: 'badge-social-butterfly',
  },
  {
    id: 'cc-financial-freedom',
    title: 'Financial Freedom Month',
    description: 'Save $1000 and track every expense for 30 days.',
    category: 'wealth',
    duration: '30 days',
    xpValue: 2500,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 1023,
    badgeId: 'badge-financial-freedom',
    microGoals: [
      { id: 'mg-1', title: 'Save $250', completed: false, xpValue: 500 },
      { id: 'mg-2', title: 'Save $500', completed: false, xpValue: 500 },
      { id: 'mg-3', title: 'Save $750', completed: false, xpValue: 500 },
      { id: 'mg-4', title: 'Save $1000', completed: false, xpValue: 1000 },
    ],
  },
  {
    id: 'cc-fitness-beast',
    title: 'Fitness Beast Mode',
    description: 'Work out 6 days a week for 4 weeks straight.',
    category: 'health',
    duration: '28 days',
    xpValue: 2200,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 2134,
    badgeId: 'badge-fitness-beast',
  },
];
