import { Quest, CategoryType, MicroGoal } from '@/types';
import { QUEST_XP_VALUES } from './categories';

export const DEFAULT_SHORT_TERM_QUESTS: Omit<Quest, 'id' | 'status' | 'startDate'>[] = [
  {
    type: 'short',
    category: 'health',
    title: 'Workout 5× this week',
    description: 'Complete 5 workout sessions in 7 days',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Workout day 1', completed: false, xpValue: 70 },
      { id: '2', title: 'Workout day 2', completed: false, xpValue: 70 },
      { id: '3', title: 'Workout day 3', completed: false, xpValue: 70 },
      { id: '4', title: 'Workout day 4', completed: false, xpValue: 70 },
      { id: '5', title: 'Workout day 5', completed: false, xpValue: 70 },
    ],
  },
  {
    type: 'short',
    category: 'health',
    title: 'Track nutrition for a week',
    description: 'Log all meals for 7 consecutive days',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'wealth',
    title: 'Save $500 this month',
    description: 'Put aside $500 into savings',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Save $100', completed: false, xpValue: 70 },
      { id: '2', title: 'Save $200', completed: false, xpValue: 70 },
      { id: '3', title: 'Save $300', completed: false, xpValue: 70 },
      { id: '4', title: 'Save $400', completed: false, xpValue: 70 },
      { id: '5', title: 'Save $500', completed: false, xpValue: 70 },
    ],
  },
  {
    type: 'short',
    category: 'wealth',
    title: 'Create a weekly budget',
    description: 'Plan and track expenses for a week',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'social',
    title: 'Meet 3 new people',
    description: 'Have meaningful conversations with 3 new people this week',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Meet person 1', completed: false, xpValue: 116 },
      { id: '2', title: 'Meet person 2', completed: false, xpValue: 117 },
      { id: '3', title: 'Meet person 3', completed: false, xpValue: 117 },
    ],
  },
  {
    type: 'short',
    category: 'social',
    title: 'Reconnect with old friends',
    description: 'Reach out to 5 friends you haven\'t talked to in a while',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'discipline',
    title: 'Wake up at 6 AM for a week',
    description: 'Maintain early wake-up routine for 7 days',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Day 1', completed: false, xpValue: 50 },
      { id: '2', title: 'Day 2', completed: false, xpValue: 50 },
      { id: '3', title: 'Day 3', completed: false, xpValue: 50 },
      { id: '4', title: 'Day 4', completed: false, xpValue: 50 },
      { id: '5', title: 'Day 5', completed: false, xpValue: 50 },
      { id: '6', title: 'Day 6', completed: false, xpValue: 50 },
      { id: '7', title: 'Day 7', completed: false, xpValue: 50 },
    ],
  },
  {
    type: 'short',
    category: 'discipline',
    title: 'Complete all daily tasks for a week',
    description: 'Don\'t skip any planned activities for 7 days',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'mental',
    title: 'Read a book',
    description: 'Finish reading one complete book',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'mental',
    title: 'Learn a new skill basics',
    description: 'Complete introductory course or tutorial',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'recovery',
    title: 'One week sober',
    description: 'Maintain sobriety for 7 consecutive days',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Day 1', completed: false, xpValue: 50 },
      { id: '2', title: 'Day 2', completed: false, xpValue: 50 },
      { id: '3', title: 'Day 3', completed: false, xpValue: 50 },
      { id: '4', title: 'Day 4', completed: false, xpValue: 50 },
      { id: '5', title: 'Day 5', completed: false, xpValue: 50 },
      { id: '6', title: 'Day 6', completed: false, xpValue: 50 },
      { id: '7', title: 'Day 7', completed: false, xpValue: 50 },
    ],
  },
  {
    type: 'short',
    category: 'recovery',
    title: 'Attend support sessions',
    description: 'Participate in 3 support group meetings',
    xpValue: QUEST_XP_VALUES.short,
  },
];

export const DEFAULT_LONG_TERM_QUESTS: Omit<Quest, 'id' | 'status' | 'startDate'>[] = [
  {
    type: 'long',
    category: 'health',
    title: 'Lose 10 lbs in 3 months',
    description: 'Achieve healthy weight loss through diet and exercise',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: 'Lose 2 lbs', completed: false, xpValue: 300 },
      { id: '2', title: 'Lose 4 lbs', completed: false, xpValue: 300 },
      { id: '3', title: 'Lose 6 lbs', completed: false, xpValue: 300 },
      { id: '4', title: 'Lose 8 lbs', completed: false, xpValue: 300 },
      { id: '5', title: 'Lose 10 lbs', completed: false, xpValue: 300 },
    ],
  },
  {
    type: 'long',
    category: 'health',
    title: 'Run a 5K',
    description: 'Train for and complete a 5K race',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'wealth',
    title: 'Invest $5,000 this year',
    description: 'Build investment portfolio',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: 'Invest $1,000', completed: false, xpValue: 300 },
      { id: '2', title: 'Invest $2,000', completed: false, xpValue: 300 },
      { id: '3', title: 'Invest $3,000', completed: false, xpValue: 300 },
      { id: '4', title: 'Invest $4,000', completed: false, xpValue: 300 },
      { id: '5', title: 'Invest $5,000', completed: false, xpValue: 300 },
    ],
  },
  {
    type: 'long',
    category: 'wealth',
    title: 'Get a promotion or raise',
    description: 'Advance in your career',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'social',
    title: 'Host an event',
    description: 'Organize and host a social gathering',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'social',
    title: 'Build a friendship group',
    description: 'Cultivate 5+ meaningful friendships',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'discipline',
    title: 'Build a morning routine',
    description: 'Maintain consistent morning habits for 90 days',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: '30 days streak', completed: false, xpValue: 500 },
      { id: '2', title: '60 days streak', completed: false, xpValue: 500 },
      { id: '3', title: '90 days streak', completed: false, xpValue: 500 },
    ],
  },
  {
    type: 'long',
    category: 'discipline',
    title: 'Complete 75 Hard',
    description: 'Finish the 75 Hard challenge',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'mental',
    title: 'Master a new skill',
    description: 'Achieve proficiency in a new area',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'mental',
    title: 'Read 12 books in a year',
    description: 'Complete one book per month',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: 'Book 1', completed: false, xpValue: 125 },
      { id: '2', title: 'Book 2', completed: false, xpValue: 125 },
      { id: '3', title: 'Book 3', completed: false, xpValue: 125 },
      { id: '4', title: 'Book 4', completed: false, xpValue: 125 },
      { id: '5', title: 'Book 5', completed: false, xpValue: 125 },
      { id: '6', title: 'Book 6', completed: false, xpValue: 125 },
      { id: '7', title: 'Book 7', completed: false, xpValue: 125 },
      { id: '8', title: 'Book 8', completed: false, xpValue: 125 },
      { id: '9', title: 'Book 9', completed: false, xpValue: 125 },
      { id: '10', title: 'Book 10', completed: false, xpValue: 125 },
      { id: '11', title: 'Book 11', completed: false, xpValue: 125 },
      { id: '12', title: 'Book 12', completed: false, xpValue: 125 },
    ],
  },
  {
    type: 'long',
    category: 'recovery',
    title: '90 days sober',
    description: 'Achieve 90 consecutive days of sobriety',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: '30 days', completed: false, xpValue: 500 },
      { id: '2', title: '60 days', completed: false, xpValue: 500 },
      { id: '3', title: '90 days', completed: false, xpValue: 500 },
    ],
  },
  {
    type: 'long',
    category: 'recovery',
    title: 'Complete therapy program',
    description: 'Finish a structured recovery program',
    xpValue: QUEST_XP_VALUES.long,
  },
];

export const DEFAULT_DAILY_QUESTS: Omit<Quest, 'id' | 'status' | 'startDate'>[] = [
  {
    type: 'daily',
    category: 'health',
    title: 'Complete a workout',
    description: 'Get 30+ minutes of physical activity',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Eat a healthy meal',
    description: 'Track your nutrition for one meal',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Track your expenses',
    description: 'Log at least one transaction',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Learn about finance',
    description: 'Read or watch 15 minutes of financial content',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Start a conversation',
    description: 'Have a meaningful conversation with someone new',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Check in with a friend',
    description: 'Reach out to someone you care about',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Wake up on time',
    description: 'Get up at your target wake time',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Complete morning routine',
    description: 'Finish your morning routine without rushing',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Read for 20 minutes',
    description: 'Read a book, article, or educational content',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Practice mindfulness',
    description: 'Meditate or journal for 10 minutes',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Stay on track',
    description: 'Maintain your recovery goals for today',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Practice self-care',
    description: 'Do something kind for yourself',
    xpValue: QUEST_XP_VALUES.daily,
  },
];


