import { Quest, CategoryType, MicroGoal } from '@/types';
import { QUEST_XP_VALUES } from './categories';

export const DEFAULT_SHORT_TERM_QUESTS: Omit<Quest, 'id' | 'status' | 'startDate'>[] = [
  {
    type: 'short',
    category: 'health',
    title: 'Workout 5× this week',
    description: 'Complete 5 workout sessions in 7 days',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Workout day 1', completed: false, xpValue: 70 },
      { id: '2', title: 'Workout day 2', completed: false, xpValue: 70 },
      { id: '3', title: 'Workout day 3', completed: false, xpValue: 70 },
      { id: '4', title: 'Workout day 4', completed: false, xpValue: 70 },
      { id: '5', title: 'Workout day 5', completed: false, xpValue: 70 },
    ],
  },
  {
    type: 'short',
    category: 'health',
    title: 'Track nutrition for a week',
    description: 'Log all meals for 7 consecutive days',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'wealth',
    title: 'Save $500 this month',
    description: 'Put aside $500 into savings',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Save $100', completed: false, xpValue: 70 },
      { id: '2', title: 'Save $200', completed: false, xpValue: 70 },
      { id: '3', title: 'Save $300', completed: false, xpValue: 70 },
      { id: '4', title: 'Save $400', completed: false, xpValue: 70 },
      { id: '5', title: 'Save $500', completed: false, xpValue: 70 },
    ],
  },
  {
    type: 'short',
    category: 'wealth',
    title: 'Create a weekly budget',
    description: 'Plan and track expenses for a week',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'social',
    title: 'Meet 3 new people',
    description: 'Have meaningful conversations with 3 new people this week',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Meet person 1', completed: false, xpValue: 116 },
      { id: '2', title: 'Meet person 2', completed: false, xpValue: 117 },
      { id: '3', title: 'Meet person 3', completed: false, xpValue: 117 },
    ],
  },
  {
    type: 'short',
    category: 'social',
    title: 'Reconnect with old friends',
    description: 'Reach out to 5 friends you haven\'t talked to in a while',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'discipline',
    title: 'Wake up at 6 AM for a week',
    description: 'Maintain early wake-up routine for 7 days',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Day 1', completed: false, xpValue: 50 },
      { id: '2', title: 'Day 2', completed: false, xpValue: 50 },
      { id: '3', title: 'Day 3', completed: false, xpValue: 50 },
      { id: '4', title: 'Day 4', completed: false, xpValue: 50 },
      { id: '5', title: 'Day 5', completed: false, xpValue: 50 },
      { id: '6', title: 'Day 6', completed: false, xpValue: 50 },
      { id: '7', title: 'Day 7', completed: false, xpValue: 50 },
    ],
  },
  {
    type: 'short',
    category: 'discipline',
    title: 'Complete all daily tasks for a week',
    description: 'Don\'t skip any planned activities for 7 days',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'mental',
    title: 'Read a book',
    description: 'Finish reading one complete book',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'mental',
    title: 'Learn a new skill basics',
    description: 'Complete introductory course or tutorial',
    xpValue: QUEST_XP_VALUES.short,
  },
  {
    type: 'short',
    category: 'recovery',
    title: 'One week sober',
    description: 'Maintain sobriety for 7 consecutive days',
    xpValue: QUEST_XP_VALUES.short,
    microGoals: [
      { id: '1', title: 'Day 1', completed: false, xpValue: 50 },
      { id: '2', title: 'Day 2', completed: false, xpValue: 50 },
      { id: '3', title: 'Day 3', completed: false, xpValue: 50 },
      { id: '4', title: 'Day 4', completed: false, xpValue: 50 },
      { id: '5', title: 'Day 5', completed: false, xpValue: 50 },
      { id: '6', title: 'Day 6', completed: false, xpValue: 50 },
      { id: '7', title: 'Day 7', completed: false, xpValue: 50 },
    ],
  },
  {
    type: 'short',
    category: 'recovery',
    title: 'Attend support sessions',
    description: 'Participate in 3 support group meetings',
    xpValue: QUEST_XP_VALUES.short,
  },
];

export const DEFAULT_LONG_TERM_QUESTS: Omit<Quest, 'id' | 'status' | 'startDate'>[] = [
  {
    type: 'long',
    category: 'health',
    title: 'Lose 10 lbs in 3 months',
    description: 'Achieve healthy weight loss through diet and exercise',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: 'Lose 2 lbs', completed: false, xpValue: 300 },
      { id: '2', title: 'Lose 4 lbs', completed: false, xpValue: 300 },
      { id: '3', title: 'Lose 6 lbs', completed: false, xpValue: 300 },
      { id: '4', title: 'Lose 8 lbs', completed: false, xpValue: 300 },
      { id: '5', title: 'Lose 10 lbs', completed: false, xpValue: 300 },
    ],
  },
  {
    type: 'long',
    category: 'health',
    title: 'Run a 5K',
    description: 'Train for and complete a 5K race',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'wealth',
    title: 'Invest $5,000 this year',
    description: 'Build investment portfolio',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: 'Invest $1,000', completed: false, xpValue: 300 },
      { id: '2', title: 'Invest $2,000', completed: false, xpValue: 300 },
      { id: '3', title: 'Invest $3,000', completed: false, xpValue: 300 },
      { id: '4', title: 'Invest $4,000', completed: false, xpValue: 300 },
      { id: '5', title: 'Invest $5,000', completed: false, xpValue: 300 },
    ],
  },
  {
    type: 'long',
    category: 'wealth',
    title: 'Get a promotion or raise',
    description: 'Advance in your career',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'social',
    title: 'Host an event',
    description: 'Organize and host a social gathering',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'social',
    title: 'Build a friendship group',
    description: 'Cultivate 5+ meaningful friendships',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'discipline',
    title: 'Build a morning routine',
    description: 'Maintain consistent morning habits for 90 days',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: '30 days streak', completed: false, xpValue: 500 },
      { id: '2', title: '60 days streak', completed: false, xpValue: 500 },
      { id: '3', title: '90 days streak', completed: false, xpValue: 500 },
    ],
  },
  {
    type: 'long',
    category: 'discipline',
    title: 'Complete 75 Hard',
    description: 'Finish the 75 Hard challenge',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'mental',
    title: 'Master a new skill',
    description: 'Achieve proficiency in a new area',
    xpValue: QUEST_XP_VALUES.long,
  },
  {
    type: 'long',
    category: 'mental',
    title: 'Read 12 books in a year',
    description: 'Complete one book per month',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: 'Book 1', completed: false, xpValue: 125 },
      { id: '2', title: 'Book 2', completed: false, xpValue: 125 },
      { id: '3', title: 'Book 3', completed: false, xpValue: 125 },
      { id: '4', title: 'Book 4', completed: false, xpValue: 125 },
      { id: '5', title: 'Book 5', completed: false, xpValue: 125 },
      { id: '6', title: 'Book 6', completed: false, xpValue: 125 },
      { id: '7', title: 'Book 7', completed: false, xpValue: 125 },
      { id: '8', title: 'Book 8', completed: false, xpValue: 125 },
      { id: '9', title: 'Book 9', completed: false, xpValue: 125 },
      { id: '10', title: 'Book 10', completed: false, xpValue: 125 },
      { id: '11', title: 'Book 11', completed: false, xpValue: 125 },
      { id: '12', title: 'Book 12', completed: false, xpValue: 125 },
    ],
  },
  {
    type: 'long',
    category: 'recovery',
    title: '90 days sober',
    description: 'Achieve 90 consecutive days of sobriety',
    xpValue: QUEST_XP_VALUES.long,
    microGoals: [
      { id: '1', title: '30 days', completed: false, xpValue: 500 },
      { id: '2', title: '60 days', completed: false, xpValue: 500 },
      { id: '3', title: '90 days', completed: false, xpValue: 500 },
    ],
  },
  {
    type: 'long',
    category: 'recovery',
    title: 'Complete therapy program',
    description: 'Finish a structured recovery program',
    xpValue: QUEST_XP_VALUES.long,
  },
];

export const DEFAULT_DAILY_QUESTS: Omit<Quest, 'id' | 'status' | 'startDate'>[] = [
  {
    type: 'daily',
    category: 'health',
    title: 'Complete a workout',
    description: 'Get 30+ minutes of physical activity',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Eat a healthy meal',
    description: 'Track your nutrition for one meal',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Drink 8 glasses of water',
    description: 'Stay hydrated throughout the day',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Take a 15-minute walk',
    description: 'Get some fresh air and movement',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Stretch for 10 minutes',
    description: 'Improve flexibility and reduce tension',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Get 8 hours of sleep',
    description: 'Prioritize rest and recovery',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Take vitamins/supplements',
    description: 'Maintain your supplement routine',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Avoid junk food',
    description: 'Make healthy food choices today',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Do 20 push-ups',
    description: 'Build upper body strength',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Practice yoga',
    description: 'Connect body and mind for 15 minutes',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Cook a healthy meal',
    description: 'Prepare nutritious food at home',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Take stairs instead of elevator',
    description: 'Choose active transportation',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Do a HIIT workout',
    description: 'Complete a high-intensity interval training session',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Avoid caffeine after 2 PM',
    description: 'Improve sleep quality',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'health',
    title: 'Practice good posture',
    description: 'Be mindful of your posture all day',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Track your expenses',
    description: 'Log at least one transaction',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Learn about finance',
    description: 'Read or watch 15 minutes of financial content',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Review your budget',
    description: 'Check spending against your budget',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Save money today',
    description: 'Put aside at least $5 into savings',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'No impulse purchases',
    description: 'Resist buying things you don\'t need',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Work on side hustle',
    description: 'Spend 30 minutes on income-generating project',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Update financial spreadsheet',
    description: 'Keep your financial records current',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Research investment options',
    description: 'Learn about a new investment opportunity',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Pack lunch instead of buying',
    description: 'Save money by bringing food from home',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Review subscriptions',
    description: 'Check for services you can cancel',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Complete a work task',
    description: 'Finish an important professional task',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Network with someone',
    description: 'Make a professional connection',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Learn a career skill',
    description: 'Study something valuable for your career',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Organize finances',
    description: 'Sort bills, receipts, or documents',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'wealth',
    title: 'Calculate net worth',
    description: 'Update your assets and liabilities',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Start a conversation',
    description: 'Have a meaningful conversation with someone new',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Check in with a friend',
    description: 'Reach out to someone you care about',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Give someone a compliment',
    description: 'Make someone\'s day brighter',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Help someone',
    description: 'Do a kind act for another person',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Make eye contact in conversations',
    description: 'Practice confident body language',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Join a group activity',
    description: 'Participate in a social event',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Practice active listening',
    description: 'Give someone your full attention',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Share something personal',
    description: 'Be vulnerable with someone you trust',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Attend a social event',
    description: 'Put yourself out there',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Express gratitude',
    description: 'Thank someone who helped you',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Send a thoughtful message',
    description: 'Reach out with care and intention',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Introduce two people',
    description: 'Create a new connection',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Smile at strangers',
    description: 'Spread positivity',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Plan a hangout',
    description: 'Organize something with friends',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'social',
    title: 'Practice small talk',
    description: 'Build conversation skills',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Wake up on time',
    description: 'Get up at your target wake time',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Complete morning routine',
    description: 'Finish your morning routine without rushing',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Make your bed',
    description: 'Start the day with a small win',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'No phone for 1 hour after waking',
    description: 'Start your day mindfully',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Complete your to-do list',
    description: 'Finish all planned tasks',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Cold shower',
    description: 'Build mental toughness',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'No social media today',
    description: 'Take a break from scrolling',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Plan tomorrow today',
    description: 'Set yourself up for success',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Do the hardest task first',
    description: 'Eat that frog',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Stick to your schedule',
    description: 'Follow your time blocks',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'No snacking after dinner',
    description: 'Practice eating discipline',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Clean your space',
    description: 'Organize your environment',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Say no to something',
    description: 'Practice setting boundaries',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Track your habits',
    description: 'Log your daily habits',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'discipline',
    title: 'Work out at scheduled time',
    description: 'Don\'t skip your workout',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Read for 20 minutes',
    description: 'Read a book, article, or educational content',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Practice mindfulness',
    description: 'Meditate or journal for 10 minutes',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Write in gratitude journal',
    description: 'List 3 things you\'re grateful for',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Learn something new',
    description: 'Take a course or watch educational content',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Practice deep breathing',
    description: '5 minutes of breathing exercises',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Solve a puzzle',
    description: 'Do a crossword, sudoku, or brain teaser',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Write morning pages',
    description: 'Stream of consciousness journaling',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Practice visualization',
    description: 'Visualize your goals for 10 minutes',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Limit news consumption',
    description: 'Avoid doomscrolling',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Practice positive affirmations',
    description: 'Speak kindly to yourself',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Listen to a podcast',
    description: 'Learn from an educational podcast',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Spend time in nature',
    description: 'Connect with the outdoors',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Create something',
    description: 'Draw, write, or make something',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Reflect on your day',
    description: 'Evening journaling session',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'mental',
    title: 'Practice mindful eating',
    description: 'Eat one meal without distractions',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Stay on track',
    description: 'Maintain your recovery goals for today',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Practice self-care',
    description: 'Do something kind for yourself',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Attend a meeting',
    description: 'Go to a support group meeting',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Call your sponsor',
    description: 'Connect with your support person',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Read recovery literature',
    description: 'Spend 15 minutes reading',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Avoid triggers',
    description: 'Stay away from people, places, or things that tempt you',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Work a step',
    description: 'Make progress in your program',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Practice HALT check-in',
    description: 'Check if you\'re Hungry, Angry, Lonely, or Tired',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Celebrate a small win',
    description: 'Acknowledge your progress',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Help another person in recovery',
    description: 'Give back to the community',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Practice coping skills',
    description: 'Use healthy strategies to manage stress',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Set a boundary',
    description: 'Protect your recovery',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Track your mood',
    description: 'Journal about your emotional state',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Practice mindfulness meditation',
    description: 'Ground yourself in the present moment',
    xpValue: QUEST_XP_VALUES.daily,
  },
  {
    type: 'daily',
    category: 'recovery',
    title: 'Reach out when struggling',
    description: 'Don\'t isolate - ask for help if needed',
    xpValue: QUEST_XP_VALUES.daily,
  },
];


